const types = {
  UPDATE_LOGIN_CK: 'UPDATE_LOGIN_CK' as const,
  UPDATE_FCM_TOKEN: 'UPDATE_FCM_TOKEN' as const,
  UPDATE_ORDER_DETAIL: 'UPDATE_ORDER_DETAIL' as const,
  UPDATE_INDEX: 'UPDATE_INDEX' as const,
  UPDATE_STORE: 'UPDATE_STORE' as const,
  CLOSED_STORE: 'CLOSED_STORE' as const,
  SELECT_STORE: 'SELECT_STORE' as const,
  UPDATE_COUPON_LIST: 'UPDATE_COUPON_LIST' as const,
  UPDATE_REGULAR_HOLIDAY: 'UPDATE_REGULAR_HOLIDAY' as const,
  UPDATE_STORE_TIME: 'UPDATE_STORE_TIME' as const,
  UPDATE_CLOSED_LIST: 'UPDATE_CLOSED_LIST' as const,
  UPDATE_NEW_ORDER_LIST: 'UPDATE_NEW_ORDER_LIST' as const,
  UPDATE_CHECK_ORDER_LIST: 'UPDATE_CHECK_ORDER_LIST' as const,
  UPDATE_DELIVERY_ORDER_LIST: 'UPDATE_DELIVERY_ORDER_LIST' as const,
  UPDATE_DONE_ORDER_LIST: 'UPDATE_DONE_ORDER_LIST' as const,
  TOGGLE_NEW_ORDER_LIST: 'TOGGLE_NEW_ORDER_LIST' as const
};

export default types;
